tasks:
  - name: Start Docker services
    init: |
      sudo service docker start
      mkdir -p ./data/momentum-srv-postgres
      mkdir -p ./data/neo4j-data
      mkdir -p ./data/pgadmin
      mkdir -p ./data/mongodb_data
      mkdir -p ./data/redis
      mkdir -p ./data/weaviate
      sudo chown -R gitpod:gitpod ./data
      docker-compose up -d
    command: |
      docker-compose logs -f

ports:
  - port: 5432
    onOpen: open-preview
  - port: 7474
    onOpen: open-preview
  - port: 7687
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 27017
    onOpen: open-preview
  - port: 6379
    onOpen: open-preview
  - port: 8082
    onOpen: open-preview
  - port: 50051
    onOpen: open-preview
  - port: 8081
    onOpen: open-preview
  - port: 8001
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
