version: '1.0'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: momentum
    ports:
      - "5432:5432"
    volumes:
      - ./data/momentum-srv-postgres:/var/lib/postgresql/data/

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/mysecretpassword
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j-data:/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: vn.sh@outlook.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

volumes:
  postgres-data:
  neo4j-data:
